CREATE OR REPLACE FUNCTION inserirRegistro(COLETA numeric(8,3), DATACOLETA DATE, HIDROMETROCOLETA INTEGER)
RETURNS VOID AS
$$
DECLARE
	REGRAID INTEGER;
	REGRAPERIODO INTEGER;
	VALORPERIODO NUMERIC;
	VALORINICIOPERIODO NUMERIC;
	VALORFIMPERIODO NUMERIC;
	REGRAVALOR NUMERIC;
	DESCRICAOREGRA VARCHAR(100);
	DATAPERIODO DATE;
BEGIN
	IF ((SELECT ATIVO FROM HIDROMETRO WHERE ID = HIDROMETROFK) = 1) THEN
		INSERT INTO REGISTRO (VALOR, DATA, HIDROMETROFK)
		VALUES (COLETA, DATACOLETA, HIDROMETROCOLETA);

		IF (SELECT COUNT(ID) FROM REGRA WHERE HIDROMETROFK = HIDROMETROCOLETA AND ATIVO = 1) > 0 THEN --EXISTEM REGRAS ATIVAS
			REGRAPERIODO := (SELECT PERIODO FROM REGRA WHERE HIDROMETROFK = HIDROMETROCOLETA);
			REGRAVALOR := (SELECT VALOR FROM REGRA WHERE HIDROMETROFK = HIDROMETROCOLETA);
			REGRAID := (SELECT ID FROM REGRA WHERE HIDROMETROFK = HIDROMETROCOLETA);
			DATAPERIODO := (SELECT dt_inicio_periodo FROM REGRA WHERE HIDROMETROFK = HIDROMETROCOLETA);

			--Caso o periodo tenha passado, considerar o novo periodo de acordo com a regra;
			IF ((DATAPERIODO + REGRAPERIODO) <  NOW()) THEN
				UPDATE REGRA SET dt_inicio_periodo = now() WHERE HIDROMETROFK = HIDROMETROCOLETA AND REGRAID = ID;
				DATAPERIODO := NOW();
			END IF;

			VALORINICIOPERIODO := (SELECT MIN(VALOR) FROM REGISTRO WHERE DATA BETWEEN DATAPERIODO AND (DATAPERIODO + REGRAPERIODO));
			VALORFIMPERIODO := (SELECT MAX(VALOR) FROM REGISTRO WHERE DATA BETWEEN DATAPERIODO AND (DATAPERIODO + REGRAPERIODO));
			--raise notice 'Valor total do periodo informado - % em % dias',VALORPERIODO,REGRAPERIODO;

			VALORPERIODO := VALORFIMPERIODO - VALORINICIOPERIODO;

			IF(VALORPERIODO > REGRAVALOR) THEN
				IF(SELECT REGRATIPOFK FROM REGRA WHERE HIDROMETROFK = HIDROMETROCOLETA) = 2 THEN -- REGRA DE CONSUMO
					DESCRICAOREGRA := CONCAT('Valor gasto no periodo: ',VALORPERIODO);
					INSERT INTO ALERTA (DESCRICAO, DATA, HIDROMETROFK, REGRAFK, REGRA)
					VALUES (DESCRICAOREGRA,DATACOLETA,HIDROMETROCOLETA,REGRAID, CONCAT('Consumo - Valor Maximo: ',cast(REGRAVALOR as varchar(100))));
				ELSE
					DESCRICAOREGRA := CONCAT('O registro apresentou um consumo fora do comum estipulado.');
					INSERT INTO ALERTA (DESCRICAO, DATA, HIDROMETROFK, REGRAFK, REGRA)
					VALUES (DESCRICAOREGRA,DATACOLETA,HIDROMETROCOLETA,REGRAID, CONCAT('Surto - Valor Maximo: ',cast(REGRAVALOR as varchar(100))));
				END IF;
			END IF;
		END IF;
	END IF;
END;   
$$
language 'plpgsql';